import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/homepage/NavBar";
import Footer from "@/components/homepage/Footer";
import ProductsProvider from "@/providers/ProductsProvider";
import ToastWrapper from "@/components/toastwrapper/ToastWrapper";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const montSerrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montSerrat.variable} ${roboto.variable}`}>
        {children}
        <ToastWrapper />
      </body>
    </html>
  );
}

{
  /* https://www.figma.com/design/nsM3mxZlRtvkMxuF4vkqez/Emmable--e-Commerce-Website-Design-Desktop-Version--Preview-?node-id=302-2&p=f&t=XflvNq8g6mgOKZq1-0 */
}
