import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/homepage/NavBar";
import Footer from "@/components/homepage/Footer";
import ProductsProvider from "@/providers/ProductsProvider";
import ToastWrapper from "@/components/toastwrapper/ToastWrapper";
import CartPageProvider from "@/providers/CartPageProvider";
import HomePageProvider from "@/providers/HomePageProvider";
import { AuthProvider } from "@/providers/AuthProvider";
import MyOrderProvider from "@/providers/MyOrderProvider";
import OrderProvider from "@/providers/OrderProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const montSerrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montSerrat.variable} ${roboto.variable}`}>
        <HomePageProvider>
          <OrderProvider>
            <MyOrderProvider>
              <AuthProvider>
                <CartPageProvider>
                  <ProductsProvider>
                    {/* <NavBar /> */}
                    {children}
                    {/* <Footer /> */}
                    <ToastWrapper />
                  </ProductsProvider>
                </CartPageProvider>
              </AuthProvider>
            </MyOrderProvider>
          </OrderProvider>
        </HomePageProvider>
      </body>
    </html>
  );
}

{
  /* https://www.figma.com/design/nsM3mxZlRtvkMxuF4vkqez/Emmable--e-Commerce-Website-Design-Desktop-Version--Preview-?node-id=302-2&p=f&t=XflvNq8g6mgOKZq1-0 */
}
